version: "3.9"
services:
  weather:
    container_name: weather
    build: .
    networks:
      - nginx-network
    external_links:
      - nginx
  weather_docks:
    container_name: weather_docs
    build: docs
    networks:
      - nginx-network
    external_links:
      - nginx

networks:
  nginx-network:
    external: true